### ISSUE TITLE
Add 'tags' parameter to ec2_lc module

### ISSUE THREAD

**Issue by sebastien-rosset** [ansible-collections/community.aws#888]
### Summary

I would like to be able to specify tags in the EC2 launch templates, such that EC2 instances and volumes are tagged when they are created.

### Issue Type

Feature Idea

### Component Name

ec2_lc

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by markuman** [comment]
`ec2_lc` != ec2 launch template  

`ec2_lc` is the old ec2 launch configuration. It's only useable for with the EC2 AutoScaling Group and does not support tags. Tags are only  inherited from AutoScaling Group in case of launch configuration - imo.

`ec2_launch_template` is the newer construct from AWS and also recommended, because you cannot use it exclusive from AutoScaling Group.

imo, the `tags` parameter in `ec2_launch_template` works already like that. Tags are already inherited by the volumes.

**Comment by tremble** [comment]
@sebastien-rosset,

Thanks for taking the time to open this issue.

Looking into Autoscaling Launch Configs (`ec2_lc` now renamed `autoscaling_launch_config`), the backend API doesn't appear to support tagging launch configs.  As such, ec2_lc can't be updated to support tagging.

However, from the rest of the description, it looks like you're actually after EC2 Launch Templates.  The `ec2_launch_template` module already supported tagging.  We also have the ec2_tags` module which can tag any EC2 resource that supports tagging.


I suspect that the confusion here is a side effect of the old name for the `ec2_lc` module.  Unfortunately this is a hangover from when the collections were a part of the main Ansible repository and we didn't have an `aws` namespace to live under.  A number of the older modules ended up prefixed with `ec2_` just because "EC2" == "AWS", rather than because they're actually a part of the EC2 APIs.  We've just done a big rename to try and avoid this confusion in future.

Because of everything above, I'm going to close out this issue.
